// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMController.Data;

#nullable disable

namespace VMController.Migrations.ProcessosRPA
{
    [DbContext(typeof(ProcessosRPAContext))]
    [Migration("20240701224958_Inicial-criacao")]
    partial class Inicialcriacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VMController.Models.ProcessosRPA", b =>
                {
                    b.Property<int>("IdProcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProcesso"), 1L, 1);

                    b.Property<int>("IdVM")
                        .HasColumnType("int");

                    b.Property<string>("NomeProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProcesso");

                    b.HasIndex("IdVM");

                    b.ToTable("ProcessosRPA");
                });

            modelBuilder.Entity("VMController.Models.VirtualMachine", b =>
                {
                    b.Property<int>("idVM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVM"), 1L, 1);

                    b.Property<float>("CapacidadeHoras")
                        .HasColumnType("real");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemoriaRam")
                        .HasColumnType("int");

                    b.Property<string>("Processador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idVM");

                    b.ToTable("VirtualMachine");
                });

            modelBuilder.Entity("VMController.Models.ProcessosRPA", b =>
                {
                    b.HasOne("VMController.Models.VirtualMachine", "VirtualMachine")
                        .WithMany()
                        .HasForeignKey("IdVM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualMachine");
                });
#pragma warning restore 612, 618
        }
    }
}
