// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMController.Data;

#nullable disable

namespace VMController.Migrations.ContextoVMMigrations
{
    [DbContext(typeof(ContextoVM))]
    partial class ContextoVMModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VMController.Models.VirtualMachine", b =>
                {
                    b.Property<int>("idVM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVM"), 1L, 1);

                    b.Property<float>("CapacidadeHoras")
                        .HasColumnType("real");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemoriaRam")
                        .HasColumnType("int");

                    b.Property<string>("Processador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idVM");

                    b.ToTable("VirtualMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
